name: hipster_mvc
version: 0.2.11
description: Dart-based MVC framework
author: Chris Strom <chris@eeecomputes.com>
homepage: https://github.com/eee-c/hipster-mvc
dependencies:
  browser: ">=0.6.19 <0.6.20"
  unittest: ">=0.6.19 <0.6.20"
  plummbur_kruk: ">=0.0.4 <0.0.5"
