name: hipster_mvc
version: 0.2.12
description: Dart-based MVC framework
author: Chris Strom <chris@eeecomputes.com>
homepage: https://github.com/eee-c/hipster-mvc
dependencies:
  browser: ">=0.8.1 <0.8.2"
dev_dependencies:
  unittest: any
  plummbur_kruk: any
